# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: { python: "3.10" }
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry 1.2.0b3
      - asdf global poetry 1.2.0b3
      - poetry config virtualenvs.create false
      - poetry plugin add poetry-dynamic-versioning-plugin
    post_install:
      - poetry install --without=dev

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
